### ISSUE TITLE
errors when converting tags

### ISSUE THREAD

**Issue by SuperMario20** [TheGuardians/TagTool#9]
When I put this in: 

converttag objects\characters\odst\odst.bipd "C:\Users\super\Desktop\ms23\maps\tag_list.csv" "C:\Users\super\Desktop\Halo Online - Copy - Copy\maps\tag_list.csv" "C:\Users\super\Desktop\Halo Online - Copy - Copy\maps"

I get this back:

Reading C:\Users\super\Desktop\ms23\maps\tag_list.csv...

CONVERTING FROM VERSION 1.106708 cert_ms23 TO 1.106708 cert_ms23

bipd 000027D6 [Offset = 0x33B04A0, Size = 0xA90]
ERROR: No `TagStructureAttribute` for `HaloOnline106708` found on `TagStructure`.
STACKTRACE:
   at TagTool.Tags.TagStructureInfo.Analyze(Type mainType, CacheVersion version)
   at TagTool.Tags.TagStructure.VersionedCache.GetTagStructureInfo(Type type, CacheVersion version)
   at TagTool.Commands.Tags.ConvertTagCommand.ConvertStructure[T](T data, HaloOnlineCacheContext srcCacheContext, Stream srcStream, HaloOnlineCacheContext destCacheContext, Stream destStream, TagVersionMap tagMap)
   at TagTool.Commands.Tags.ConvertTagCommand.Convert(Object data, HaloOnlineCacheContext srcCacheContext, Stream srcStream, HaloOnlineCacheContext destCacheContext, Stream destStream, TagVersionMap tagMap)
   at TagTool.Commands.Tags.ConvertTagCommand.ConvertTag(CachedTagInstance srcTag, HaloOnlineCacheContext srcCacheContext, Stream srcStream, HaloOnlineCacheContext destCacheContext, Stream destStream, TagVersionMap tagMap)
   at TagTool.Commands.Tags.ConvertTagCommand.Execute(List`1 args)
   at TagTool.Commands.Program.ExecuteCommand(CommandContext context, List`1 commandAndArgs)

When I put this in: 

converttag "objects\characters\odst\odst.bipd" "C:\Users\super\Desktop\Halo Online (12.1.700255 2015-11-24)\maps\tag_list.csv" "C:\Users\super\Desktop\Halo Online - Copy - Copy\maps\tag_list.csv" "C:\Users\super\Desktop\Halo Online - Copy - Copy\maps"

I get this back:

Reading C:\Users\super\Desktop\Halo Online (12.1.700255 2015-11-24)\maps\tag_list.csv...

CONVERTING FROM VERSION 12.1.700123 cert_ms30_oct19 TO 1.106708 cert_ms23

bipd 000056E3 [Offset = 0x9C82270, Size = 0xA90]
ERROR: No `TagStructureAttribute` for `HaloOnline106708` found on `TagStructure`.
STACKTRACE:
   at TagTool.Tags.TagStructureInfo.Analyze(Type mainType, CacheVersion version)
   at TagTool.Tags.TagStructure.VersionedCache.GetTagStructureInfo(Type type, CacheVersion version)
   at TagTool.Commands.Tags.ConvertTagCommand.ConvertStructure[T](T data, HaloOnlineCacheContext srcCacheContext, Stream srcStream, HaloOnlineCacheContext destCacheContext, Stream destStream, TagVersionMap tagMap)
   at TagTool.Commands.Tags.ConvertTagCommand.Convert(Object data, HaloOnlineCacheContext srcCacheContext, Stream srcStream, HaloOnlineCacheContext destCacheContext, Stream destStream, TagVersionMap tagMap)
   at TagTool.Commands.Tags.ConvertTagCommand.ConvertTag(CachedTagInstance srcTag, HaloOnlineCacheContext srcCacheContext, Stream srcStream, HaloOnlineCacheContext destCacheContext, Stream destStream, TagVersionMap tagMap)
   at TagTool.Commands.Tags.ConvertTagCommand.Execute(List`1 args)
   at TagTool.Commands.Program.ExecuteCommand(CommandContext context, List`1 commandAndArgs)

**Comment by SuperMario20** [comment]
what am I doing wrong?
